import { DocumentStatus, RecordStatus, RoleCode } from '@prisma/client';
import ExcelJS from 'exceljs';
import { access } from 'node:fs/promises';
import path from 'node:path';
import { Router, type Response } from 'express';
import { z } from 'zod';
import { HttpError } from '../lib/http-error.js';
import { prisma } from '../lib/prisma.js';
import { authenticate, requireRole } from '../middleware/auth.js';
import { writeOperationLog } from '../services/operation-log.service.js';

const router = Router();
const idSchema = z.object({ id: z.string().uuid() });
const chooseOptionsSchema = z.object({ includeSpec: z.coerce.boolean().default(true), includeCost: z.coerce.boolean().default(false), includeImage: z.coerce.boolean().default(false) }).strict();
const materialsSchema = z.object({ keyword: z.string().trim().max(150).optional(), color: z.string().trim().max(100).optional(), status: z.nativeEnum(RecordStatus).optional(), categoryId: z.string().uuid().optional(), providerId: z.string().uuid().optional(), includeImage: z.coerce.boolean().default(false) }).strict();
router.use(authenticate, requireRole(RoleCode.ADMIN, RoleCode.STAFF));
function download(res: Response, workbook: ExcelJS.Workbook, name: string) { res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'); res.setHeader('Content-Disposition', `attachment; filename="${encodeURIComponent(name)}"`); return workbook.xlsx.write(res).then(() => res.end()); }

router.post('/sample-chooses/:id', async (req, res, next) => { try {
  const { id } = idSchema.parse(req.params); const options = chooseOptionsSchema.parse(req.body ?? {}); if (options.includeCost && req.auth!.role !== RoleCode.ADMIN) throw new HttpError(403, '员工无权导出成本');
  const choose = await prisma.sampleChoose.findUnique({ where: { id }, include: { customer: true, items: { include: { material: { include: { images: { orderBy: { sortOrder: 'asc' } } } } } } } }); if (!choose) throw new HttpError(404, '客户选样单不存在'); if (choose.status !== DocumentStatus.ACTIVE) throw new HttpError(400, '已作废单据不可导出');
  const workbook = new ExcelJS.Workbook(); const sheet = workbook.addWorksheet('客户选样'); sheet.columns = [{ header: '单号', key: 'documentNo', width: 20 }, { header: '客户', key: 'customer', width: 20 }, { header: 'Item No', key: 'itemNo', width: 20 }, { header: '面料名称', key: 'name', width: 24 }, ...(options.includeSpec ? [{ header: '规格', key: 'specification', width: 30 }] : []), { header: '数量', key: 'quantity', width: 12 }, { header: '单位', key: 'unit', width: 10 }, { header: '备注', key: 'remark', width: 24 }, ...(options.includeCost ? [{ header: '成本', key: 'cost', width: 14 }] : []), ...(options.includeImage ? [{ header: '图片 URL', key: 'imageUrl', width: 40 }] : [])];
  sheet.getRow(1).font = { bold: true }; for (const item of choose.items) { const imageUrl = item.material.images[0]?.url ?? ''; const row = sheet.addRow({ documentNo: choose.documentNo, customer: choose.customerName, itemNo: item.itemNoSnapshot, name: item.nameSnapshot, specification: item.specSnapshot?.trim() || '/', quantity: item.quantity, unit: item.material.unit, remark: item.remark, cost: item.material.cost?.toString(), imageUrl }); if (options.includeImage && imageUrl.startsWith('/uploads/')) { const file = path.resolve(process.cwd(), imageUrl.slice(1)); try { await access(file); const imageId = workbook.addImage({ filename: file, extension: path.extname(file).slice(1) as 'jpeg' | 'png' | 'gif' }); sheet.addImage(imageId, { tl: { col: sheet.columns.length - 1, row: row.number - 1 }, ext: { width: 80, height: 80 } }); row.height = 65; } catch { /* 图片 URL 已保留 */ } } }
  await writeOperationLog({ userId: req.auth!.userId, action: 'EXPORT', resource: 'SAMPLE_CHOOSE', resourceId: id, detail: options, ip: req.ip }); await download(res, workbook, `${choose.documentNo}.xlsx`);
} catch (error) { next(error); } });

router.get('/materials', async (req, res, next) => { try {
  const query = materialsSchema.parse(req.query); if (req.auth!.role !== RoleCode.ADMIN && query.providerId) throw new HttpError(403, '员工无权按供应商导出');
  const where = { ...(query.status ? { status: query.status as unknown as RecordStatus } : {}), ...(query.categoryId ? { categoryId: query.categoryId } : {}), ...(query.color ? { color: { contains: query.color, mode: 'insensitive' as const } } : {}), ...(req.auth!.role === RoleCode.ADMIN && query.providerId ? { providerId: query.providerId } : {}), ...(query.keyword ? { OR: [{ itemNo: { contains: query.keyword, mode: 'insensitive' as const } }, { name: { contains: query.keyword, mode: 'insensitive' as const } }, { specification: { contains: query.keyword, mode: 'insensitive' as const } }, { color: { contains: query.keyword, mode: 'insensitive' as const } }] } : {}) };
  const materials = await prisma.materialFabric.findMany({ where, include: { category: { select: { name: true } }, ...(req.auth!.role === RoleCode.ADMIN ? { provider: { select: { name: true } } } : {}), images: { orderBy: { sortOrder: 'asc' } } }, orderBy: [{ updatedAt: 'desc' }, { itemNo: 'asc' }] });
  const admin = req.auth!.role === RoleCode.ADMIN; const workbook = new ExcelJS.Workbook(); const sheet = workbook.addWorksheet('面料资料'); sheet.columns = [{ header: 'Item No.', key: 'itemNo', width: 20 }, { header: '名称', key: 'name', width: 24 }, { header: '类别', key: 'category', width: 18 }, { header: '规格', key: 'specification', width: 26 }, { header: '成分', key: 'composition', width: 22 }, { header: '组织', key: 'construction', width: 18 }, { header: '幅宽', key: 'width', width: 14 }, { header: '克重', key: 'weight', width: 14 }, { header: '颜色', key: 'color', width: 16 }, { header: '单位', key: 'unit', width: 10 }, { header: '状态', key: 'status', width: 10 }, ...(admin ? [{ header: '供应商', key: 'provider', width: 20 }, { header: '成本', key: 'cost', width: 14 }] : []), ...(query.includeImage ? [{ header: '图片', key: 'imageUrl', width: 40 }] : [])]; sheet.getRow(1).font = { bold: true };
  for (const material of materials) { const imageUrl = material.images[0]?.url ?? ''; const row = sheet.addRow({ itemNo: material.itemNo, name: material.name, category: material.category.name, specification: material.specification?.trim() || '/', composition: material.composition ?? '', construction: material.construction ?? '', width: material.width ?? '', weight: material.weight ?? '', color: material.color ?? '', unit: material.unit, status: material.status === RecordStatus.ACTIVE ? '启用' : '停用', provider: admin ? material.provider?.name ?? '' : undefined, cost: admin ? material.cost?.toString() ?? '' : undefined, imageUrl }); if (query.includeImage && imageUrl.startsWith('/uploads/')) { const file = path.resolve(process.cwd(), imageUrl.slice(1)); try { await access(file); const extension = path.extname(file).slice(1).toLowerCase(); if (extension === 'jpg' || extension === 'jpeg' || extension === 'png' || extension === 'gif') { const imageId = workbook.addImage({ filename: file, extension: extension === 'jpg' ? 'jpeg' : extension as 'jpeg' | 'png' | 'gif' }); sheet.addImage(imageId, { tl: { col: sheet.columns.length - 1, row: row.number - 1 }, ext: { width: 80, height: 80 } }); row.height = 65; } } catch { /* URL remains as fallback */ } } }
  await writeOperationLog({ userId: req.auth!.userId, action: 'EXPORT', resource: 'MATERIAL_FABRIC', detail: query, ip: req.ip }); await download(res, workbook, '面料资料.xlsx');
} catch (error) { next(error); } });

export default router;
