import path from 'node:path';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import { rateLimit } from 'express-rate-limit';
import { env } from './config/env.js';
import { ok } from './lib/api-response.js';
import authRouter from './routes/auth.js';
import systemRouter from './routes/system.js';
import categoriesRouter from './routes/categories.js';
import partnersRouter from './routes/partners.js';
import sampleCustomersRouter from './routes/sample-customers.js';
import dictionariesRouter from './routes/dictionaries.js';
import materialsRouter from './routes/materials.js';
import usersRouter from './routes/users.js';
import sampleChoosesRouter from './routes/sample-chooses.js';
import exportsRouter from './routes/exports.js';
import labelsRouter from './routes/labels.js';
import { errorHandler } from './middleware/error-handler.js';

export const app = express();
const rateLimitError = (_req: express.Request, res: express.Response) => res.status(429).json({ code: 429, message: '请求过于频繁，请稍后再试', data: null });
const createLimiter = (max: number) => rateLimit({ windowMs: 15 * 60 * 1000, limit: max, standardHeaders: 'draft-8', legacyHeaders: false, handler: rateLimitError });
const corsOrigins = env.CORS_ORIGIN.split(',').map((origin) => origin.trim()).filter(Boolean);
app.set('trust proxy', 1);
app.use(helmet());
app.use(cors({ origin: corsOrigins.length ? corsOrigins : false, credentials: false }));
app.use(express.json({ limit: '1mb' }));
app.use('/uploads', express.static(path.resolve(process.cwd(), 'uploads')));
app.get('/health', (_req, res) => ok(res, { status: 'ok' }));
app.use('/api/auth/login', createLimiter(env.AUTH_LOGIN_RATE_LIMIT_MAX));
app.use('/api/auth/refresh', createLimiter(env.AUTH_REFRESH_RATE_LIMIT_MAX));
app.use('/api/auth', authRouter);
app.use('/api/categories', categoriesRouter);
app.use('/api', partnersRouter);
app.use('/api/sample-customers', sampleCustomersRouter);
app.use('/api/dictionaries', dictionariesRouter);
app.use('/api/materials/:id/images', createLimiter(env.UPLOAD_RATE_LIMIT_MAX));
app.use('/api/materials', materialsRouter);
app.use('/api/sample-chooses', sampleChoosesRouter);
app.use('/api/exports', exportsRouter);
app.use('/api/labels', labelsRouter);
app.use('/api/system/users', usersRouter);
app.use('/api/system', systemRouter);
app.use((_req, res) => res.status(404).json({ code: 404, message: '接口不存在', data: null }));
app.use(errorHandler);
