import { useEffect, useMemo, useState } from 'react'
import { ChevronDown, ChevronRight } from 'lucide-react'
import PageHeader from '@/components/PageHeader'
import { api } from '@/lib/api'

type Category = { id: string; name: string; parentId?: string | null; sortOrder: number; status: 'ACTIVE' | 'DISABLED'; parent?: { id: string; name: string } | null }
type Draft = { name: string; parentId: string; sortOrder: string }

export default function CategoryTree() {
  const [items, setItems] = useState<Category[]>([])
  const [expanded, setExpanded] = useState<Set<string>>(new Set())
  const [keyword, setKeyword] = useState('')
  const [status, setStatus] = useState('')
  const [draft, setDraft] = useState<Draft | null>(null)
  const [editing, setEditing] = useState<Category | null>(null)
  const [message, setMessage] = useState('')
  const [loading, setLoading] = useState(false)

  const load = async () => { setLoading(true); setMessage(''); try { const result = await api.get<{ list: Category[] }>('/categories?pageSize=100'); setItems(result.list); setExpanded(new Set(result.list.map((item) => item.id))) } catch (error) { setMessage(error instanceof Error ? error.message : '加载失败') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const children = useMemo(() => { const map = new Map<string, Category[]>(); items.forEach((item) => { const key = item.parentId ?? ''; map.set(key, [...(map.get(key) ?? []), item]) }); return map }, [items])
  const visibleIds = useMemo(() => { const matched = new Set(items.filter((item) => (!keyword || item.name.toLowerCase().includes(keyword.toLowerCase())) && (!status || item.status === status)).map((item) => item.id)); const ids = new Set(matched); for (const item of items) { if (!matched.has(item.id)) continue; let parentId = item.parentId; while (parentId) { ids.add(parentId); parentId = items.find((candidate) => candidate.id === parentId)?.parentId } } return ids }, [items, keyword, status])
  const forbiddenParents = useMemo(() => { const ids = new Set<string>(); if (!editing) return ids; const visit = (id: string) => { ids.add(id); (children.get(id) ?? []).forEach((item) => visit(item.id)) }; visit(editing.id); return ids }, [editing, children])
  const openCreate = (parentId = '') => { setEditing(null); setDraft({ name: '', parentId, sortOrder: '0' }) }
  const openEdit = (item: Category) => { setEditing(item); setDraft({ name: item.name, parentId: item.parentId ?? '', sortOrder: String(item.sortOrder) }) }
  const save = async () => { if (!draft || !draft.name.trim()) { setMessage('请填写类别名称'); return }; try { const payload = { name: draft.name.trim(), parentId: draft.parentId || null, sortOrder: Number(draft.sortOrder || 0) }; if (editing) await api.patch(`/categories/${editing.id}`, payload); else await api.post('/categories', payload); setDraft(null); setEditing(null); await load() } catch (error) { setMessage(error instanceof Error ? error.message : '保存失败') } }
  const toggle = async (item: Category) => { try { await api.post(`/categories/${item.id}/toggle`, { status: item.status === 'ACTIVE' ? 'DISABLED' : 'ACTIVE' }); await load() } catch (error) { setMessage(error instanceof Error ? error.message : '操作失败') } }
  const render = (parentId = '', depth = 0): JSX.Element[] => (children.get(parentId) ?? []).filter((item) => visibleIds.has(item.id)).flatMap((item) => { const hasChildren = (children.get(item.id)?.some((child) => visibleIds.has(child.id)) ?? false); return [<div key={item.id} className="flex items-center gap-2 border-b border-slate-100 py-2 text-sm" style={{ paddingLeft: `${depth * 24 + 8}px` }}>{hasChildren ? <button onClick={() => setExpanded((current) => { const next = new Set(current); if (next.has(item.id)) next.delete(item.id); else next.add(item.id); return next })}>{expanded.has(item.id) ? <ChevronDown size={16} /> : <ChevronRight size={16} />}</button> : <span className="w-4" />}<span className="min-w-40 font-medium">{item.name}</span><span className="text-slate-500">排序 {item.sortOrder}</span><span className={item.status === 'ACTIVE' ? 'text-emerald-600' : 'text-slate-400'}>{item.status === 'ACTIVE' ? '启用' : '停用'}</span><div className="ml-auto flex gap-3"><button onClick={() => openCreate(item.id)}>新增子类</button><button onClick={() => openEdit(item)}>编辑</button><button onClick={() => void toggle(item)}>{item.status === 'ACTIVE' ? '停用' : '启用'}</button></div></div>, ...(expanded.has(item.id) || keyword || status ? render(item.id, depth + 1) : [])] })
  return <div><PageHeader title="面料类别维护" description="以树状结构维护面料类别。" action="新增根类别" onAction={() => openCreate()} /><div className="mb-4 flex flex-wrap gap-3 rounded-2xl border border-slate-200 bg-white p-4"><input className="h-10 rounded-lg border border-slate-200 px-3 text-sm" placeholder="搜索类别名称" value={keyword} onChange={(event) => setKeyword(event.target.value)} /><select className="h-10 rounded-lg border border-slate-200 px-3 text-sm" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">全部状态</option><option value="ACTIVE">启用</option><option value="DISABLED">停用</option></select></div>{loading && <p className="mb-3 rounded-lg bg-slate-50 p-3 text-sm text-slate-500">加载中…</p>}{message && <p className="mb-3 rounded-lg bg-red-50 p-3 text-sm text-red-600">{message}</p>} {!loading && !items.length && <p className="rounded-lg bg-slate-50 p-3 text-sm text-slate-500">暂无类别，请新增根类别。</p>}<div className="rounded-2xl border border-slate-200 bg-white px-4">{render()}</div>{draft && <div className="fixed inset-0 z-40 bg-slate-900/40 p-6"><div className="mx-auto max-w-md rounded-2xl bg-white p-6"><h2 className="mb-4 text-lg font-bold">{editing ? '编辑类别' : '新增类别'}</h2><label className="mb-3 block text-sm">类别名称<input className="mt-1 w-full rounded-lg border border-slate-200 p-2" value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label className="mb-3 block text-sm">父级<select className="mt-1 w-full rounded-lg border border-slate-200 p-2" value={draft.parentId} onChange={(event) => setDraft({ ...draft, parentId: event.target.value })}><option value="">无（根类别）</option>{items.filter((item) => !forbiddenParents.has(item.id)).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="block text-sm">排序<input type="number" min="0" className="mt-1 w-full rounded-lg border border-slate-200 p-2" value={draft.sortOrder} onChange={(event) => setDraft({ ...draft, sortOrder: event.target.value })} /></label><div className="mt-5 flex gap-3"><button className="rounded-lg border border-slate-200 px-4 py-2 text-sm" onClick={() => setDraft(null)}>取消</button><button className="rounded-lg bg-[#123c5a] px-4 py-2 text-sm text-white" onClick={() => void save()}>保存</button></div></div></div>}</div>
}
